### ISSUE TITLE
Feature request: Brighter orange

### ISSUE THREAD

**Issue by spxak1** [ful1e5/fuchsia-cursor#11]
Hi, thanks for this amazing set of mouse pointers.

I use the Pop version and I wish it was brighter as it doesn't stand out much from the (mostly) white background.

I use Pop and it is a nice touch that it matches Pop's orange colour, but could there be one more version with a more contrasting orange, like e.g the one used for the bibata amber?

Many thanks again!

**Comment by ful1e5** [comment]
I plan to release this cursor set in the upcoming release, Inshallah, Fuchsia Amber :relieved: .

Thanks for your patience!

**Comment by spxak1** [comment]
> I plan to release this cursor set in the upcoming release, Inshallah, Fuchsia Amber 😌 .
> 
> Thanks for your patience!

Thank you for the update. Much appreciated.

**Comment by ful1e5** [comment]
Officially available in [v2.0.1](https://github.com/ful1e5/fuchsia-cursor/releases/tag/v2.0.1)
