### ISSUE TITLE
Color Request: Black, White and Grey/Dark

### ISSUE THREAD

**Issue by DewenHona** [ful1e5/fuchsia-cursor#13]
This is perfect need these colors

**Comment by beeaniebee** [comment]
I created a fork with a black theme. It has an added white outline for better visibility. Check it out and see if that's what you're looking for!

**Comment by ful1e5** [comment]
@DewenHona, check out this [Reddit reply](https://www.reddit.com/r/unixporn/comments/1dow0ji/comment/lan48hq/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).
