### ISSUE TITLE
The 'busy' and 'work' cursor seems to animate too fast on windows

### ISSUE THREAD

**Issue by KotlinIsland** [ful1e5/fuchsia-cursor#4]
How are they supposed to look?

**Comment by ful1e5** [comment]
fixed in [v1.0.3](https://github.com/ful1e5/fuchsia-cursor/releases/tag/v1.0.3)

**Comment by KotlinIsland** [comment]
the 'work' cursor still seems to animate faster than the 'busy' indicator
